# Generated by Django 5.2.4 on 2025-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(related_name='products_available_in', to='product.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='existing_brands',
            field=models.ManyToManyField(related_name='products_available_in', to='product.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='products_with_color', to='product.color'),
        ),
    ]
