# Generated by Django 5.2.4 on 2025-08-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_color_remove_product_existing_brands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='products_with_color', to='product.color'),
        ),
    ]
