# Generated by Django 5.2.4 on 2025-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erjan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
